services:
  - type: web
    name: yandex-travel-parser
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install chromium
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
